### ISSUE TITLE
Prepare a Wedding

### ISSUE THREAD

**Issue by obuchtala** [obuchtala/swig#10]
Gather tasks and find collaborators for merging the javascript module into SWIG's main tree.

Travis: [![Build Status](https://travis-ci.org/oliver----/swig-v8.png)](https://travis-ci.org/oliver----/swig-v8)

**Comment by obuchtala** [comment]
@lefticus, @whoozle, @ewmailing:
Thanks for your work in the last time.
Are you interested in helping?

Cheers,
Oliver

**Comment by whoozle** [comment]
@oliver---- yes, I am interested and I have no choice :) Someone (me or someone from my team) would definitely support swig-v8 either in my branch and/or in mainline, because we use swig in our project :)

**Comment by obuchtala** [comment]
Great!

I am currently fixing my setup and will come up with a plan in some hours.

You have to tell me a more about your project (curious :) ) -  but maybe not on this thread.

**Comment by whoozle** [comment]
skype me if you want, the same nickname.

**Comment by lefticus** [comment]
I'm also interested in helping out some, but I don't know how much time I'll have.

Looking at this history, it looks like you already did the merging of our forks and rebasing against the mainline SWIG? 

That leaves documentation and unit test cleanups, for the most part, correct?

**Comment by obuchtala** [comment]
@lefticus Great! :) yep, rebase is done.

Some tasks that spring into my mind
- dynamic control over the v8 version compatibility:
  we should achieve that we can control the v8 compatibility via command a line arg.
- Documentation:
  we should have a more common style of documentation
- Travis-CI support:
  we should discuss with William how to address our multi-target module.
- Testing on all platforms:
  also we need to discuss with Wiliiam which platform versions need to be considered
- Configuration:
  we need improvements so that the test- and example-suite runs out-of-the-box

Probably we will have to fix some bugs on the way, too.

@whoozle, @lefticus : what do you think? What are your preferences?

Cheers,
Oliver

**Comment by whoozle** [comment]
@oliver---- I have trouble rebasing, becase my work was based on @lefticus branch and I made more modification supporting the most recent v8 api changes. So, merging your upstream + rebasing on that commit fails. :( I think I need to extract my commits as patches and apply on your swig branch and then follow it as "upsteam". So it would take some time.

**Comment by obuchtala** [comment]
Hmmm, sorry for that.
Yes, using patches is probably the easiest way.

**Comment by obuchtala** [comment]
@whoozle BTW, have you seen that I had rebased your change b7ea0385d9f3625a4de3d50649dcc64779779915 already?

**Comment by ewmailing** [comment]
On 9/1/13, Oliver Buchtala notifications@github.com wrote:

> Hmmm, sorry for that.
> Yes, using patches is probably the easiest way.

So I already merged my stuff with most of the other branches here. I
don't really understand rebasing. Is my stuff completely unmergable
now and lost?

**Comment by obuchtala** [comment]
No it's not lost...
Send me a link to your upstream commit, then I will do the rebasing for you.

**Comment by obuchtala** [comment]
However, you should try to learn that.

From the git documentation: https://www.kernel.org/pub/software/scm/git/docs/git-rebase.html 

Here is how you would transplant a topic branch based on one branch to another, to pretend that you forked the topic branch from the latter branch, using rebase --onto.

First let’s assume your topic is based on branch next. For example, a feature developed in topic depends on some functionality which is found in next.

```
o---o---o---o---o  master
     \
      o---o---o---o---o  next
                       \
                        o---o---o  topic
```

We want to make topic forked from branch master; for example, because the functionality on which topic depends was merged into the more stable master branch. We want our tree to look like this:

```
o---o---o---o---o  master
    |            \
    |             o'--o'--o'  topic
     \
      o---o---o---o---o  next
```

We can get this using the following command:

git rebase --onto master next topic

**Comment by obuchtala** [comment]
@ewmailing see https://github.com/oliver----/swig-v8/tree/ewmailing_devel

What i did: (starting from my devel branch)
1. Fetch your repos
2. See what is a common root (semantically) between our indexes: 0732592ed99759afab2f05e6be1723659e955464
3. Create a local branch
4. Move it to the common root commit
5. Take the corresponding sha in your index: c7b4cf9580c473f84ed97302c4df363b59e87352
6. Take the latest: 6d73f929f4e698357de0f8f84b0b08a0f43e13b1
7. Doing the rebase as in the documentation
8. Setting the branch head to the correct commit

``` bash
$ git fetch ewmailing devel
$ git checkout -b ewmailing_devel
$ git reset --hard 0732592ed99759afab2f05e6be1723659e955464
$ git rebase --onto ewmailing_devel 5dbccef640700ff3517d8e55ebd3fdc2e9ac9f5e 6d73f929f4e698357de0f8f84b0b08a0f43e13b1
$ git log -1
commit 692e2fa231c400bdac6543295102253ef0c8911d
$ git checkout ewmailing_devel
$ git reset --hard 692e2fa231c400bdac6543295102253ef0c8911d
```

Probably, this can be improved a lot by using more advanced command line flags (e.g., the resetting stuff is clumsy). However, this is where I stopped learning... as I can achieve my tasks.

**Comment by ewmailing** [comment]
On 9/3/13, Oliver Buchtala notifications@github.com wrote:

> @ewmailing see https://github.com/oliver----/swig-v8/tree/ewmailing_devel
> 
> What i did: (starting from my devel branch)
> 1. Fetch your repos
> 2. See what is a common root (semantically) between our indexes:
>    0732592ed99759afab2f05e6be1723659e955464
> 3. Create a local branch
> 4. Move it to the common root commit
> 5. Take the corresponding sha in your index:
>    c7b4cf9580c473f84ed97302c4df363b59e87352
> 6. Take the latest: 6d73f929f4e698357de0f8f84b0b08a0f43e13b1
> 7. Doing the rebase as in the documentation
> 8. Setting the branch head to the correct commit
> 
> ``` bash
> $ git fetch ewmailing devel
> $ git checkout -b ewmailing_devel
> $ git reset --hard 0732592ed99759afab2f05e6be1723659e955464
> $ git rebase --onto ewmailing_devel 5dbccef640700ff3517d8e55ebd3fdc2e9ac9f5e
> 6d73f929f4e698357de0f8f84b0b08a0f43e13b1
> $ git log -1
> commit 692e2fa231c400bdac6543295102253ef0c8911d
> $ git checkout ewmailing_devel
> $ git reset --hard 692e2fa231c400bdac6543295102253ef0c8911d
> ```
> 
> Probably, this can be improved a lot by using more advanced command line
> flags (e.g., the resetting stuff is clumsy). However, this is where I
> stopped learning... as I can achieve my tasks.

So I'm still confused by this. But I've manually been comparing the
changesets and files. It looks like you already got most of my stuff
and omitted the api version stuff which is fine.

But this one is missing from your branch. Can you comment on this?
https://github.com/ewmailing/swig-v8/commit/e012131a6de2c260f28fbf373950eed639e5f6c0

I see you some how were able to fix this without taking this commit:
https://github.com/ewmailing/swig-v8/commit/642946af437c8f88469d98947c5584f918447d9f

And you omitted this, but I think things are now working without it.
https://github.com/ewmailing/swig-v8/commit/5dbccef640700ff3517d8e55ebd3fdc2e9ac9f5e

**Comment by whoozle** [comment]
Sorry to intercept your discussion, I failed to rebase too, so I cloned repo once again and fixed such one-liners in new repo. It turned out to be faster than merging all these branches, missing commits and the upstream. Maybe it will save you some time. :)

**Comment by obuchtala** [comment]
@ewmailing Thanks for your summary.

642946af437c8f88469d98947c5584f918447d9f
-> It seems that this change came also from another commit... dunno. It looks different now...

5dbccef640700ff3517d8e55ebd3fdc2e9ac9f5e
-> I somehow missed that one :( Thanks!

**Comment by obuchtala** [comment]
Naaa. Effects of 5dbccef are in place....
So I think everything is fine...

**Comment by obuchtala** [comment]
I am working currently on getting the full test-suite compilable.
However this does not mean that things are actually working 'semantically'.

Would anyone like to join adding test runners? Comparing to other tasks, this is rather enjoyable :)
