### ISSUE TITLE
%rename not fully working in v8 and jsc

### ISSUE THREAD

**Issue by ewmailing** [obuchtala/swig#18]
While working with issue #16, I discovered %rename isn't fully working. In the unit test included at the bottom, I create a private constant called MYINFINITY so I can reference the real INFINITY (because it is often defined by compiler built-ins). I then use %rename to restore the binding name to INFINITY.

In v8, this incorrect line gets generated:
SWIGV8_AddStaticVariable(infinity_obj, "MYINFINITY", _wrap_INFINITY_get, JS_veto_set_variable);

In JSCore, this incorrect line gets generated:
    "MYINFINITY", _wrap_INFINITY_get, JS_veto_set_variable, kJSPropertyAttributeNone

Notice in both cases, the string name is "MYINFINITY" when it should be "INFINITY". But of note, the function _wrap_INFINITY_get did get renamed.

Unit test: infinity.i
%module infinity
# include <math.h>

// C99 defines INFINITY
// Because INFINITY may be defined by compiler built-ins, we can't use #define.
// Instead, expose the variable MYINFINITY and then use %rename to make it INFINITY in the scripting language.
%rename(INFINITY) MYINFINITY;

%inline %{
# include <math.h>

const double MYINFINITY = INFINITY;

// Use of float is intentional because the original bug was in the float conversion
float use_infinity(float inf_val)
{
    return inf_val;
}
%}

**Comment by ewmailing** [comment]
I think I figured out a fix for this rename problem.
In exitVariable, if I change the lines that look like:
          .replace(T_NAME, state.variable(NAME))
to
          .replace(T_NAME, Swig_name_mangle(state.variable(NAME)))
this fixes the problem. 

Using state.variable(NAME_MANGLED) does not work though.

This might suggest there are more places that need Swig_name_mangle() to account for the possibility of %rename being in use.

**Comment by obuchtala** [comment]
Thanks.
You are absolutely right...
I have to revisit all the places and consider usage of 
Swig_name_mangle() where it is possible.

**Comment by ewmailing** [comment]
Drat. I tried applying the same Swig_name_mangle() technique to the JSCore implementation, but it doesn't have any effect in my test case. Any ideas?

**Comment by obuchtala** [comment]
Not yet.
I will have a closer look on monday.

**Comment by obuchtala** [comment]
I will activate and fix the `rename*` test-cases.

**Comment by obuchtala** [comment]
`rename_simple` and `rename_scope` reveal errors (see https://travis-ci.org/oliver----/swig-v8/builds/11146920).
I will address them today.

**Comment by obuchtala** [comment]
Done.
