### ISSUE TITLE
$result not being substituted for custom typemaps

### ISSUE THREAD

**Issue by ewmailing** [obuchtala/swig#31]
$result is supposed to be a valid variable for certain typemaps, but it doesn't get replaced in the code generation.

Simple example:
%typemap(argout) float\* out_value
{
    $result = JSValueMakeNumber(context, *$1);
}

I believe this is a bug in both the JSCore and V8 implementations.

**Comment by obuchtala** [comment]
Supposedly this has been fixed in the meantime.
At least, there are tests such as 'typemap_variables' which indicate that this is working.
