### ISSUE TITLE
Need typemaps.i for JSCore and v8

### ISSUE THREAD

**Issue by ewmailing** [obuchtala/swig#32]
typemaps.i is still not implemented for either of these platforms. This is really handy because writing typemaps is advanced stuff and makes entry into SWIG or generating from existing .i files (written for other languages) that assume this exists, more difficult.

**Comment by obuchtala** [comment]
It is there: bb7bd50eabdf5cc2f07640227713ef75dc1c8fce

We are using the UTL here, which does a lot.
