### ISSUE TITLE
Some SWIG functions are missing the static modifier (SWIGINTERN or SWIGRUNTIME) which causes duplicate symbol errors

### ISSUE THREAD

**Issue by ewmailing** [obuchtala/swig#34]
Some of the generated SWIG helper functions are missing the static modifier, so if you try to compile and link 2 separate SWIG based modules together, duplicate symbol errors occur.

This is a problem in both sets of JavaScript files (JSCore and v8). 

I still have my old branch from before you rebased. I applied some initial fixes to my own branch. They were pretty simple. Here are the commits:

https://github.com/ewmailing/swig-v8/commit/07a77f8e5a859dfe9c28786023f92ecd98202238
https://github.com/ewmailing/swig-v8/commit/6db53ee354621f6aa26869fbed6e89db3166a088

The two files I found were in:
javascripthelpers.swg
javascriptruntime.swg 

There may be others, but these were the only ones that stopped my specific program from linking in JSCore. I applied similar fixes to v8, but I don't have a good test because my v8 environment uses dynamic plugins instead of static linking so I don't get the compiler help.

**Comment by obuchtala** [comment]
Fixed via aa55154ccfa967297181e886a350a36b03c64e07 and 8498e4878d130a6ae24843084408339f3bf910ce
