### ISSUE TITLE
JSCore initialize signature changed and is no longer registering the namespace

### ISSUE THREAD

**Issue by ewmailing** [obuchtala/swig#38]
I'm looking at mainline. I discovered that the initialize function now has a second parameter, JSObjectRef\* exports, and no longer registers the namespace. 

I figured out that I need this code at the end of initialize to restore the previous behavior:
    {
        JSObjectRef global_object;
        global_object = JSContextGetGlobalObject(context);  
        JS_registerNamespace(context, exports_object, global_object, "$jsname");
    }

As it stands, I can't externalize this implementation because JS_registerNamespace is a SWIG internal function. Additionally, the name will cause duplicate symbol problems with 2 SWIG modules in the same program. (I think I have another bug about this already filed.)

**Comment by obuchtala** [comment]
You can use JSObjectSetProperty.
