### ISSUE TITLE
SWIGJSC_AppendOutput forgets to return a value

### ISSUE THREAD

**Issue by ewmailing** [obuchtala/swig#39]
In javascriptrun.swg,
JSValueRef SWIGJSC_AppendOutput(JSContextRef context, JSValueRef value, JSValueRef obj)

needs to return a value, but forgets to do so.
I'm guessing it needs at the end:
  return arr;

**Comment by obuchtala** [comment]
Fixed via swig/swig@486e903de1bbf847a0a60aa85ab1e1a44c8ca159
