### ISSUE TITLE
JSCore: Wrapping JSValueMakeNull with JSValueToObject causes bugs (SWIG_JSC_NewPointerObj)

### ISSUE THREAD

**Issue by ewmailing** [obuchtala/swig#43]
I'm experiencing a weird behavior with SWIG_JSC_NewPointerObj

Currently the implementation does this for NULL pointers:
 if (ptr == NULL) {
  return JSValueToObject(context, JSValueMakeNull(context), 0);
}

I've discovered that this leads to problems and the type seems to get corrupted or converted down the road to kJSTypeUndefined instead of staying as kJSTypeNull. 

I see this by calling a function that returns NULL. In the debugger, I see that the type is kJSTypeNull in the SWIG glue right up to the return.
Then if I immediately call another function using the return value, I see that the type has mysteriously changed to kJSTypeUndefined.

I suspect that JSCore does not expect you to wrap JSValueRefs for Null in JSObjectRefs because they are not actual objects according to JSCore, hence we may be in undefined behavior.

After some testing, I found that the following simple change solves the problem.
 if (ptr == NULL) {
  return (JSObjectRef)JSValueMakeNull(context);
}

I think there is a bigger issue in that SWIG_JSC_NewPointerObj always returns JSObjectRefs and we don't have a version that returns JSValueRefs. I noticed most of the wrappers that are generated for me expect to return a JSValueRef (not JSObjectRef), but NewPointerObj is always used.

I'm not sure how hard it would be to try to clean this up, but it seems like more work than anybody wants to do. I have not encountered other problems like this so far, so maybe this one simple change is sufficient.

**Comment by obuchtala** [comment]
Does this explain the seggie I have observer on Travis?

**Comment by ewmailing** [comment]
On 5/19/14, Oliver Buchtala notifications@github.com wrote:

> Does this explain the seggie I have observer on Travis?

I haven't experienced any segfaults related to this, so I don't know.
But this could be related. Would you try my simple fix and see if the
segfaults disappear?

Thanks,

## Eric

Beginning iPhone Games Development
http://playcontrol.net/iphonegamebook/

**Comment by obuchtala** [comment]
Looking good.

So let's stick to the quick fix for now.
We can investigate later what it means to switch to JSValueRef as return value.

**Comment by obuchtala** [comment]
Fixed via 61b7da1671f5d88127eae0cde4561cd7883c825b

Staged: https://travis-ci.org/oliver----/swig/builds/25518868.
